version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      firebase:
        patterns:
          - "firebase_*"
          - "cloud_firestore"
          - "cloud_functions"
      freezed:
        patterns:
          - "freezed_annotation"
          - "freezed"
          - "json_annotation"
          - "json_serializable"
      riverpod:
        patterns:
          - "hooks_riverpod"
          - "riverpod_*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
