# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "lib/constants/firebase_options.dart"
    - "_flutter/**"
  plugins:
    - custom_lint
