targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/**/*.dart
            - lib/**/*_state.dart
      json_serializable:
        generate_for:
          include:
            - lib/models/**/*.dart
        options:
          checked: true
          explicit_to_json: true
