name: kingu_dev
description: portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.0.6
  firebase_app_check: ^0.1.1+3
  firebase_auth: ^4.1.5
  firebase_core: ^2.4.0
  firebase_performance: ^0.9.0+4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^5.2.1
  hooks_riverpod: ^2.1.1
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.7.0
  riverpod_annotation: ^1.0.6
  roggle: ^0.3.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  go_router_builder: ^1.0.15
  json_serializable: ^6.5.4
  pedantic_mono: ^1.18.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true
