name: kingu_dev
description: portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.2.0-0
  flutter: ^3.15.0-0

dependencies:
  firebase_analytics: ^10.5.0
  firebase_app_check: ^0.2.0
  firebase_core: ^2.16.0
  firebase_performance: ^0.9.2+6
  flame: ^1.9.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^11.1.2
  hooks_riverpod: ^2.4.1
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.0
  roggle: ^0.3.2
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  go_router_builder: ^2.3.3
  grinder: ^0.9.4
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
