name: kingu_dev
description: portfolio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.2.0-0
  flutter: ^3.17.0-0

dependencies:
  firebase_analytics: ^10.8.0
  firebase_app_check: ^0.2.1+6
  firebase_core: ^2.24.0
  firebase_performance: ^0.9.3+6
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  roggle: ^0.4.2+1
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  grinder: ^0.9.5
  json_serializable: ^6.7.1
  pedantic_mono: ^1.25.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/images/
