name: kingu_dev
description: portfolio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.4.0-0
  flutter: ^3.20.0-0

dependencies:
  dio: ^5.4.1
  firebase_analytics: ^10.8.9
  firebase_app_check: ^0.2.1+6
  firebase_core: ^2.24.0
  firebase_performance: ^0.9.3+6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  hooks_riverpod: ^2.5.1
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  roggle: ^0.4.2+1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2+4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  grinder: ^0.9.5
  json_serializable: ^6.7.1
  pedantic_mono: ^1.26.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/images/
