name: kingu_dev
description: portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.5
  firebase_app_check: ^0.0.7
  firebase_auth: ^3.7.0
  firebase_core: ^1.22.0
  firebase_performance: ^0.8.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  go_router: ^5.0.0
  hooks_riverpod: ^2.0.0-dev.9
  intl: any
  json_annotation: ^4.6.0
  roggle: ^0.2.1+1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.12
  json_serializable: ^6.4.0
  pedantic_mono: ^1.18.0

flutter:
  uses-material-design: true

assets:
  - assets/
