name: kingu_dev
description: portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.1.0-0
  flutter: ^3.11.0-1.0

dependencies:
  firebase_analytics: ^10.4.3
  firebase_app_check: ^0.1.4+3
  firebase_core: ^2.14.0
  firebase_performance: ^0.9.2+3
  flame: ^1.8.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.5
  flutter_animate: ^4.2.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^8.2.0
  hooks_riverpod: ^2.3.6
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  roggle: ^0.3.2
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  go_router_builder: ^2.1.1
  grinder: ^0.9.4
  json_serializable: ^6.7.0
  pedantic_mono: ^1.22.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
