name: kingu_dev
description: portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.1.6
  firebase_app_check: ^0.1.1+14
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_performance: ^0.9.0+16
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.2
  intersperse: ^2.0.0
  intl: any
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.2
  roggle: ^0.3.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.7
  grinder: ^0.9.3
  json_serializable: ^6.6.1
  pedantic_mono: ^1.21.1
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6
  yaml: ^3.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
