name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.3.0" # FIXME
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ### Setup ###
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Install Flutter
        run: ./.github/workflows/scripts/install-flutter.sh $FLUTTER_VERSION

      ### Build ###
      - name: Build
        run: |
          flutter pub get
          flutter build web

      ### Deploy ###
      - name: deploy
        run: |
          firebase deploy
