name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.7.7" # FIXME

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: "projects/939401085199/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@kingu-42.iam.gserviceaccount.com"

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Install Flutter
        run: ./.github/workflows/scripts/install-flutter.sh $FLUTTER_VERSION

      ### Build ###
      - name: Build
        run: |
          flutter pub get
          flutter build web

      ### Deploy ###
      - name: deploy
        run: |
          mv build/web firebase/web
          cd firebase
          firebase deploy
