name: pub get

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.7.11" # FIXME

jobs:
  pub_get:
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dart')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/cache@v3
        with:
          path: _flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install Flutter
        run: .github/workflows/scripts/install_flutter.sh $FLUTTER_VERSION

      - run: flutter pub get

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.lock
          git commit -m "fix: pubspec.lock" || true
          git push

      - name: Remove label
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'pub_get'
            })
