name: pub get

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.7.11" # FIXME

jobs:
  pub_get:
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dart')
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        uses: tibdex/github-app-token@v1.8.0
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/cache@v3
        with:
          path: _flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install Flutter
        run: .github/workflows/scripts/install_flutter.sh $FLUTTER_VERSION

      - run: flutter pub get

      - name: Commit
        run: |
          git remote set-url origin https://github-actions:${GENERATE_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.lock
          git commit -m "fix: pubspec.lock" || true
          git push
