name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - "firebase/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "beta" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: "flutter-:channel:-:version:-:hash:"

      - run: flutter --version

      - run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          git diff --exit-code

      ### Build ###
      - name: Build
        run: |
          flutter build web
