name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "beta" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - name: Install Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 3.3

      - name: Run pandoc
        run: pandoc --version

      ### Build ###
      - name: Build
        run: |
          ./convert.sh

      ### Test ###
      - name: Test
        run: |
          ./deploy_alpha.sh
