name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "beta" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - name: Install Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 3.3

      - name: Run pandoc
        run: pandoc --version

      - name: Setup Firebase CLI Dev
        uses: KoheiKanagu/composite-actions/setup-firebase-cli@main
        with:
          workload_identity_provider: "projects/939401085199/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@kingu-42.iam.gserviceaccount.com"

      ### Build ###
      - name: Build
        run: |
          ./convert.sh

      ### Test ###
      - name: Test
        run: |
          ./deploy_alpha.sh
