name: Pull Requests

on:
  workflow_run:
    workflows:
      - pub_get
    types:
      - completed
  pull_request:
    paths-ignore:
      - "firebase/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.7.10" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: _flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: "Install Flutter"
        run: .github/workflows/scripts/install_flutter.sh $FLUTTER_VERSION

      - run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          git diff --exit-code

      ### Build ###
      - name: Build
        run: |
          flutter build web
