name: Pull Requests

on:
  workflow_run:
    workflows:
      - pub_get
  pull_request:
    paths-ignore:
      - "firebase/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.7.10" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v3

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh $FLUTTER_VERSION

      - run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          git diff --exit-code

      ### Build ###
      - name: Build
        run: |
          flutter build web
