name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - "firebase/**"

env:
  FLUTTER_VERSION: "3.3.0" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v3

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh $FLUTTER_VERSION

      ### Build ###
      - name: Build
        run: |
          flutter pub get
          flutter build web
